---
title: "STA130H1S -- Fall 2022"
subtitle: Week 12 Tutorial Handout
output: pdf_document
---

#### Today's agenda (5 min):  

- Q&A/vocabulary list

- Group Presentation

- Work on final project 

#### This Week's Vocab (15-20 min) : 

- Observational study
- Confounding
- Confounded
- Association
- Causation
- Experiment
- Randomized (controlled) trial
- Control group
- Ethics/ ethical issue/ ethical consideration
- Consent
- Information
- Comprehension
- Voluntariness
- Transparent
- Web scraping
- API
- Rate-limit


#### Group Presentation (50 min) :

$~$

*I will post the following material on Quercus in advance for students to access*

Read the article on [$\text{\underline{racial disparities exposed by the COVID-19 pandemic}}$](https://www.nature.com/immersive/d41586-021-00943-x/index.html). You can also find a PDF version in Week 12 on Quercus. 

You will prepare a 10-min group presentation based on the article.

**Your assignment is as follows: suppose you came across a research study on efficacies of COVID vaccines in the general US population. The study concludes that the vaccine efficacy is the highest in Non-Hispanic Whites, and only marginally significant in the African Americans. Explain what might have contributed to the unfortunate conclusion from the study; then, design a similar trial avoiding some of the same ethical pitfalls that you identified from the original study.**

(You are encouraged to find external sources, such as statistics, studies, news, policies, that support your claims as long as you correctly cite them.) 


## Your presentation should include:

- An introduction of the problem.

- Three factors that may have contributed to differences in COVID vaccine efficacies across racial groups (hint: social determinants of health)

- Explain your trial design (e.g. sample size, participant demographics, stratification)

- What would you propose to the policy-makers based on the finding of your studies and what's written in the article

- Discuss the implication of racial disparities in pandemic and what does it mean to you. 


## Some things to keep in mind  

- The introduction should state the overall purpose of the presentation.   

- Each main point should be “signaled.” Use *signal phrases* or *signposts* to transition between your points.

- Every group member must speak during the presentation or marks will be deducted for participation.
